# Generated by Django 5.0.4 on 2024-04-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities_app', '0003_remove_subject_subjects_subject_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(blank=True, limit_choices_to={'id__lte': 7}, to='universities_app.student', verbose_name='Student'),
        ),
    ]
