# Generated by Django 5.0.4 on 2024-04-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='personal_number',
            field=models.CharField(max_length=11, verbose_name='Personal Number'),
        ),
    ]
