# Generated by Django 5.0.4 on 2024-04-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="personal_number",
            new_name="passport_number",
        ),
    ]
